# Generated by Django 3.1.2 on 2020-11-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=200)),
                ('new_body', models.TextField()),
                ('new_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_created', models.DateTimeField(auto_now_add=True)),
                ('new_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('wait_publish', 'Wait Publish')], default='draft', max_length=15)),
                ('new_slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('new_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
