# Generated by Django 3.1.2 on 2020-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('wait_publish', 'Wait Publish')], default='draft', max_length=15),
        ),
    ]
